In [1]:
import pandas as pd
import numpy as np
#import pandas and np

In [2]:
df = pd.read_csv('../data/warn.csv')
#imported the csv from the scrape

In [52]:
df_NY= df[df['county'] == 'New York County']
#saved a data frame just for New York County

,notice_date,event_number,reason,company,address,county,phone,business_type,affected,total_employees,layoff_date,dislocation,union,classification
8,5/1/2020,2019-1600,Temporary Plant Layoff,"LH Employment Services, LLC",(4 NYC sites),New York County,(212) 244-8866,Restaurant,274,274,5/1/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Layoff
14,4/28/2020,2019-1549,Temporary Plant Layoff,TripAdvisor LLC and Smarter Travel Media,"330 Hudson StreetNew York, NY 10013",New York County,(781) 800-5341,Travel Agency,52,0,5/5/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Temporary Plant Layoff
16,4/29/2020,2019-1565,Temporary Plant Layoff,"Lyft, Inc.","441 9th Avenue, Floor 2New York, NY 10001",New York County,(415) 504-2812,Transportation,53,0,5/8/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Temporary Plant Layoff
17,4/28/2020,2019-1550,Plant Layoff,"RTW Retailwinds, Inc.","330 West 34th StreetNew York, NY 10001",New York County,(212) 884-2030,Retail,192,0,5/2/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Plant Layoff
18,4/27/2020,2019-1566,Temporary Layoff,"USM, Inc.","1700 Markley St., Suite 100Norristown, PA 19401",New York County,(610) 313-2671,Janitorial Services,38,0,3/30/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Temporary Layoff
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1196,1/23/2020,2019-0242,Plant Layoff,"Walmart eCommerce (Altitude Collection, LLC)","54 W. 21ST Street, Floor 11New York, NY 10010",New York County,(650) 228-6986,Developing private incubated brands across mul...,29,56,April,Economic,The employees are not represented by a union.,Plant Layoff
1199,11/4/2019,2019-0240,Plant Layoff,"Home Box Office, Inc.","30 Hudson YardsNew York, NY 10001",New York County,(212) 512-5644,American premium channel owned by the Home Box...,2,1665,Separations,Economic,The employees are not represented by a union.,Plant Layoff
1205,1/14/2020,2019-0230,Plant Closing,Pepper Hamilton LLP,"620 Eighth Avenue, 37th FloorNew York, NY 10018",New York County,(215) 981-4657,LawFirm,51,51,3/31/2020,Merger with Troutman Sanders and to become kno...,The employees are not represented by a union.,Plant Closing
1208,1/8/2020,2019-0210,Plant Closing,"Connected Ventures, LLC (CH Media)","330 W. 34th Street, 5th FloorNew York, NY 10001",New York County,(212) 314-7366,Operates online content and retail properties,39,39,Employment,Economic,The employees are not represented by a union.,Plant Closing
1211,12/30/2019,2019-0205,Plant Closing,"127 W. 43rd St. Chophouse, Inc. (Heartland Bre...","127 West 43rd StreetNew York, NY 10018",New York County,(917) 999-6532,Restaurant,106,106,The,Economic,The employees are not represented by a union.,Plant Closing

In [5]:
df_NY['business_type'].unique()
#looked at business types in the data that are unique

array(['Restaurant', 'Travel Agency', 'Transportation', 'Retail',
       'Janitorial Services', 'Hotel',
       'Gem Research, Education, and Laboratory', 'Labor Union',
       'Social Club', 'Production Company', 'Fitness Club',
       'Legal Services', 'Food preparation and delivery services',
       'Outdoor Lounge/Restaurant', 'Event Company', 'Airline Services',
       'Plumbing and Heating',
       'Visual Effects and Post Production Services',
       'Commercial Real Estate Services', 'Interior Design',
       'Grocery Store', 'Retail Store', 'Security Services',
       'Cosmetic Manufacturer', 'Catering', 'Building Services',
       'Electric Company', 'Movie Theatre', 'PR Consulting', 'Theater',
       'Travel and Tourism', 'Consulting Group', 'Media Company',
       'Executive Events Company', 'Internet Retail', 'Broth Shop',
       'Designer, Distribution and Licensor of Apparel',
       'Payroll & HR Services', 'Museum', 'Auto Dealership',
       'Cleaning Services', 'Realty', 'Auction House',
       'Ophthalmologist/Optician', 'Software Company',
       'Community Working Space', 'Public relations', 'Theatre Company',
       'Movie Theater', 'Employment Agency', 'Courier Service',
       'Online Fitness', 'Online Recommendations',
       'Commercial real estate company', 'Jewelry Sales',
       'Network Provider', 'Airport Restaurant', 'Clothing Manufacturer',
       'Footwear Retailer', 'Bedding, Bath, and window Manufacturing',
       'Digital Marketing', 'Musical Instrument Rental', 'Day Spa',
       'Attorney', 'Law Firm', 'Security System Installation', 'Airline',
       'Closets and Storage', 'Global tech media company', 'Gym',
       'Footwear', 'Parking Service/Locations', 'Commercial Cleaning',
       'Architecture Firm', 'Transportation Company', 'Sporting Goods',
       'Social services organization',
       'an American clothing brand and retailer',
       'Modern Japanese restaurant', 'Music Venue', 'Wellness Center',
       'Real Estate', 'Portfolio Management', 'Construction',
       'Real Estate Manager and Developer', 'Animal Wellness and Care',
       'Data Analytics Service Provider',
       'Integrated Media Entertainment', 'Ticket Sales',
       'Catering Staffing', 'Audio, Visual and Lighting',
       'Denim Retailer', 'Healthcare', 'Jewelry Store', 'Coffee Shop',
       '-----', 'Airport Support', 'Interior designer',
       'French Restaurant', 'Production  Company', 'Hospitality',
       'Providing temporary and long-term housing accommodations for relocated individuals and corporate officials',
       'A global defense technology leader',
       'Viacom operates as an entertainment media company that offers television programs and motion pictures.',
       'Programs for persons with development disabilities.',
       'Members-only personal shopping and concierge service',
       'Developing private incubated brands across multiple categories of Health, Beauty, & Wellness, Fashion, and Home furnishing products.',
       'Retail Corporate offices',
       'Providing investment management and research services',
       'Retail store', 'Leading  healthcare improvement company',
       'New York City-based online monthly subscription service that sends its subscribers a box of four to five selected samples of makeup, or other beauty related products..',
       'Health and fitness center',
       'American premium channel owned by the Home Box Office, Inc.',
       'LawFirm', 'Operates online content and retail properties'],
      dtype=object)

In [29]:
df_rest= df_NY[df_NY['business_type'] == 'Restaurant'] 
df_rest
#saved a dataframe with restaurants in New York county

,notice_date,event_number,reason,company,address,county,phone,business_type,affected,total_employees,layoff_date,dislocation,union,classification
8,5/1/2020,2019-1600,Temporary Plant Layoff,"LH Employment Services, LLC",(4 NYC sites),New York County,(212) 244-8866,Restaurant,274,274,5/1/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Layoff
47,4/17/2020,2019-1527,Temporary Plant Layoff,Wolf Eastside LLC dba Wolfgang's Steakhouse,"200 East 54th StreetNew York, NY 10012",New York County,(646) 642-4655,Restaurant,65,0,3/19/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Temporary Plant Layoff
65,4/20/2020,2019-1513,Temporary Plant Closing,Gigino at Wagner Park LLC,"20 Battery PlaceNew York, NY 10004",New York County,(212) 431-1112,Restaurant,24,0,3/16/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Temporary Plant Closing
66,4/20/2020,2019-1514,Temporary Plant Layoff,Gigino Inc. dba Gigino Trattoria,"323 Greenwich StreetNew York, NY 10013",New York County,(212) 431-1112,Restaurant,38,0,3/16/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Temporary Plant Layoff
67,3/29/2020,2019-1515,Temporary Plant Closing,181 Thompson Street LLC,"181 Thompson StreetNew York, NY 10012",New York County,-----,Restaurant,120,0,3/16/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Temporary Plant Closing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1145,3/16/2020,2019-0360,Temporary Plant Closing,Great Dane OpCo LLC,"89 East 42nd StreetNew York, NY 10017",New York County,(732) 266-6799,Restaurant,170,170,7/31/2020,Unforeseeable business circumstances prompted...,The employees are not represented by a union,Temporary Plant Closing
1146,3/16/2020,2019-0361,Plant Closing,Honeycrisp USA LLC,"89 East 42nd StreetNew York, NY 10017",New York County,(732) 266- 6799,Restaurant,4,4,-----,Unforeseeable business circumstances prompted...,The employees are not represented by a union.,Temporary Plant Closing
1148,3/14/2020,2019-0352,Temporary Plant Layoff,"Madison Park Acquisitions, LLC d/b/a Black Ba...","19 E. 26th StreetNew York, NY 10009",New York County,(646) 488- 0965,Restaurant,88,90,3/10/2020,Unforeseeable business circumstances prompted...,The employees are not represented by a union.,Temporary Plant Layoff
1155,3/5/2020,2019-0343,Plant Closing,"Modell's II, Inc.",(Modell's Sporting Goods) Support Center498 7...,New York County,(212) 822-1002,Restaurant,30,0,3/17/2020,Unforeseen business circumstances as a result ...,"Local 1102 Retail, Wholesale and Department ...",Plant Closing
1211,12/30/2019,2019-0205,Plant Closing,"127 W. 43rd St. Chophouse, Inc. (Heartland Bre...","127 West 43rd StreetNew York, NY 10018",New York County,(917) 999-6532,Restaurant,106,106,The,Economic,The employees are not represented by a union.,Plant Closing

In [53]:
df_NY.loc[df_NY['business_type'].str.contains('Restaurant|restaurant|Restaurants|restaurants'), 'business_type'] = 'Restaurant'
#contained all the NY county restaurants with spelling variations

/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [47]:
df_newrest = df_NY['business_type'].value_counts().reset_index().rename(columns={'index': 'business_type', 'business_type': 'count'})
df_newrest
#changed all column values which contained the word restaurants and counted it using value_count, renamed columns

                               business_type  count
0                                 Restaurant    342
1                                      Hotel    100
2                                     Retail     10
3                          Building Services     10
4                                   Catering      9
..                                       ...    ...
107                          Wellness Center      1
108                            Jewelry Store      1
109  Leading  healthcare improvement company      1
110                               Healthcare      1
111                     Portfolio Management      1

[112 rows x 2 columns]

In [34]:
df_allrests=df_NY[df_NY['business_type'].str.contains('Restaurant|restaurant')]
#saved all restaurants variations into new variable

In [49]:
df_allrests

,notice_date,event_number,reason,company,address,county,phone,business_type,affected,total_employees,layoff_date,dislocation,union,classification
8,5/1/2020,2019-1600,Temporary Plant Layoff,"LH Employment Services, LLC",(4 NYC sites),New York County,(212) 244-8866,Restaurant,274,274,5/1/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Layoff
47,4/17/2020,2019-1527,Temporary Plant Layoff,Wolf Eastside LLC dba Wolfgang's Steakhouse,"200 East 54th StreetNew York, NY 10012",New York County,(646) 642-4655,Restaurant,65,0,3/19/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Temporary Plant Layoff
65,4/20/2020,2019-1513,Temporary Plant Closing,Gigino at Wagner Park LLC,"20 Battery PlaceNew York, NY 10004",New York County,(212) 431-1112,Restaurant,24,0,3/16/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Temporary Plant Closing
66,4/20/2020,2019-1514,Temporary Plant Layoff,Gigino Inc. dba Gigino Trattoria,"323 Greenwich StreetNew York, NY 10013",New York County,(212) 431-1112,Restaurant,38,0,3/16/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Temporary Plant Layoff
67,3/29/2020,2019-1515,Temporary Plant Closing,181 Thompson Street LLC,"181 Thompson StreetNew York, NY 10012",New York County,-----,Restaurant,120,0,3/16/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union,Temporary Plant Closing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1145,3/16/2020,2019-0360,Temporary Plant Closing,Great Dane OpCo LLC,"89 East 42nd StreetNew York, NY 10017",New York County,(732) 266-6799,Restaurant,170,170,7/31/2020,Unforeseeable business circumstances prompted...,The employees are not represented by a union,Temporary Plant Closing
1146,3/16/2020,2019-0361,Plant Closing,Honeycrisp USA LLC,"89 East 42nd StreetNew York, NY 10017",New York County,(732) 266- 6799,Restaurant,4,4,-----,Unforeseeable business circumstances prompted...,The employees are not represented by a union.,Temporary Plant Closing
1148,3/14/2020,2019-0352,Temporary Plant Layoff,"Madison Park Acquisitions, LLC d/b/a Black Ba...","19 E. 26th StreetNew York, NY 10009",New York County,(646) 488- 0965,Restaurant,88,90,3/10/2020,Unforeseeable business circumstances prompted...,The employees are not represented by a union.,Temporary Plant Layoff
1155,3/5/2020,2019-0343,Plant Closing,"Modell's II, Inc.",(Modell's Sporting Goods) Support Center498 7...,New York County,(212) 822-1002,Restaurant,30,0,3/17/2020,Unforeseen business circumstances as a result ...,"Local 1102 Retail, Wholesale and Department ...",Plant Closing
1211,12/30/2019,2019-0205,Plant Closing,"127 W. 43rd St. Chophouse, Inc. (Heartland Bre...","127 West 43rd StreetNew York, NY 10018",New York County,(917) 999-6532,Restaurant,106,106,The,Economic,The employees are not represented by a union.,Plant Closing

In [50]:
df_allrests['affected'].sum()
#all the people affected by restaurant layoffs

27326

In [42]:
df_allrests.tail()

,notice_date,event_number,reason,company,address,county,phone,business_type,affected,total_employees,layoff_date,dislocation,union,classification
1145,3/16/2020,2019-0360,Temporary Plant Closing,Great Dane OpCo LLC,"89 East 42nd StreetNew York, NY 10017",New York County,(732) 266-6799,Restaurant,170,170,7/31/2020,Unforeseeable business circumstances prompted...,The employees are not represented by a union,Temporary Plant Closing
1146,3/16/2020,2019-0361,Plant Closing,Honeycrisp USA LLC,"89 East 42nd StreetNew York, NY 10017",New York County,(732) 266- 6799,Restaurant,4,4,-----,Unforeseeable business circumstances prompted...,The employees are not represented by a union.,Temporary Plant Closing
1148,3/14/2020,2019-0352,Temporary Plant Layoff,"Madison Park Acquisitions, LLC d/b/a Black Ba...","19 E. 26th StreetNew York, NY 10009",New York County,(646) 488- 0965,Restaurant,88,90,3/10/2020,Unforeseeable business circumstances prompted...,The employees are not represented by a union.,Temporary Plant Layoff
1155,3/5/2020,2019-0343,Plant Closing,"Modell's II, Inc.",(Modell's Sporting Goods) Support Center498 7...,New York County,(212) 822-1002,Restaurant,30,0,3/17/2020,Unforeseen business circumstances as a result ...,"Local 1102 Retail, Wholesale and Department ...",Plant Closing
1211,12/30/2019,2019-0205,Plant Closing,"127 W. 43rd St. Chophouse, Inc. (Heartland Bre...","127 West 43rd StreetNew York, NY 10018",New York County,(917) 999-6532,Restaurant,106,106,The,Economic,The employees are not represented by a union.,Plant Closing

In [54]:
df_NY.groupby(['business_type'])['affected'].agg('sum').sort_values(ascending=False).reset_index()
#Looked at the people affected by layoffs by each business type

                                         business_type  affected
0                                           Restaurant     27326
1                                                Hotel     11790
2                                             Catering      1351
3                                               Retail      1023
4                            Parking Service/Locations       883
..                                                 ...       ...
107                                  Interior designer         2
108  Providing temporary and long-term housing acco...         1
109                                             Museum         0
110                                Closets and Storage         0
111                           Ophthalmologist/Optician         0

[112 rows x 2 columns]

In [55]:
df_newrest.to_csv("../data/New York layoffs.csv")